fileID = fopen('nodes.txt','w');

fprintf(fileID,'** Generated by : ImportExport Version 6.5.121.017d0ffce\n** ----------------------------------------------------------------\n**\n*Node\n');
fprintf(fileID,'%d, %8.6f, %8.6f, %8.6f\n',nodesMatrixForSave);
fprintf(fileID,'**\n** ----------------------------------------------------------------\n**\n');

fclose(fileID);
