% fileID = fopen('elements.txt','w');
% 
% fprintf(fileID,'** Generated by : ImportExport Version 6.5.121.017d0ffce\n** ----------------------------------------------------------------\n**\n*Element, type=C3D8\n');
% fprintf(fileID,'%d, %d, %d, %d, %d, %d, %d, %d, %d\n',elementsMatrixForSave);
% fprintf(fileID,'**\n** ----------------------------------------------------------------\n**\n');
% 
% fclose(fileID);

writematrix(elements,'elements.txt')
