elesetComponent = zeros([1 3]);
elesetComponent(1) = 1;
elesetComponent(2) = elementsNum;
elesetComponent(3) = 1;

fileID = fopen('eleset.txt','w');

fprintf(fileID,'** Generated by : ImportExport Version 6.5.121.017d0ffcen**\n*** ----------------------------------------------------------------\n**\n** The element sets\n*Elset, elset=cube, generate\n');
fprintf(fileID,'%d, %d, %d\n',elesetComponent);
fprintf(fileID,'**\n** Each Grain is made up of multiple elements\n**\n');

for k = 1:max(elementsMatrix(:,1))
    fprintf(fileID,'*Elset, elset=Grain%d_set\n',k);
    % Search certain row of designated value
    inputValue = k;
    idx = find(elementsMatrix(:,1)==inputValue);
    % Result of search
    resultOfinputValue = elementsMatrix(idx,:);
    value = resultOfinputValue(:,2);
    fprintf(fileID,'%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n',value);
    fprintf(fileID, '\n');
end
fprintf(fileID,'**\n** ----------------------------------------------------------------\n**\n');

fclose(fileID);
